### ISSUE TITLE
Unable to open font file

### ISSUE THREAD

**Issue by RupankarGhosh** [cmatsuoka/figlet#11]
I'm trying to compose figlet in android (Termux with Ubuntu installed) and it composed without any error.But when I run figlet it shows 

```
figlet: standard: Unable to open font file
```
# Screenshot below

![Font error in figlet](https://i.imgur.com/Bcl58bp.png)

**Comment by Oliveralr** [comment]
You're missing something, Try using the next command: 
`figlet -f fontname "hellothere"`

*Don't forget fill *fontname* with any font provided by fliget. e.g. thin, weird ,universe...

**Comment by johnb85022** [comment]
I have seen this message when the font name has a space in the name, I used quotes to get around that, for example. 
figlet -f 'DOS Rebel.flf' foo

2 cents, JB

**Comment by RupankarGhosh** [comment]
My Post of 2018 is still getting replied.cool.btw problem solved now :xD

**Comment by MRX-IOS** [comment]
> My Post of 2018 is still getting replied.cool.btw problem solved now :xD

try cp the standard.elf file to /usr/share/figlet (this is the default path of the figlet styles)
I don't know how can you get the .elf file, sorry.

**Comment by MRX-IOS** [comment]
> > My Post of 2018 is still getting replied.cool.btw problem solved now :xD
> 
> try cp the standard.elf file to /usr/share/figlet (this is the default path of the figlet styles) I don't know how can you get the .elf file, sorry.

Sorry I was wrong on the .elf file the real extension is some like .flc or .flf.
And for extra information, If don´t exist /usr/share/figlet , you can see the path with this command : 
figlet -I 2 (make sure that you put the i on capital letters)
I have to say that
I solved this problem because I have a friend with an Apple computer and in this computers you can have access to all .flf or .flc files

**Comment by freemotion21** [comment]
larry3d font not found ;(
Using termux btw
